/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Post {
  'id' : bigint,
  'media' : Uint8Array,
  'author' : Principal,
  'isFinalized' : boolean,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteChunk' : ActorMethod<[bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], boolean>,
  'finalizeUpload' : ActorMethod<[bigint], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPaginatedPosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getPost' : ActorMethod<[bigint], Post>,
  'getPostsByAuthor' : ActorMethod<[Principal], Array<Post>>,
  'getUploadState' : ActorMethod<[bigint], boolean>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUploadState' : ActorMethod<[bigint, boolean], undefined>,
  'uploadMediaChunk' : ActorMethod<
    [bigint, bigint, bigint, Uint8Array],
    boolean
  >,
  'uploadMediaData' : ActorMethod<[Uint8Array], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];