/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'media' : IDL.Vec(IDL.Nat8),
  'author' : IDL.Principal,
  'isFinalized' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteChunk' : IDL.Func([IDL.Nat], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'finalizeUpload' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPaginatedPosts' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Post)],
      ['query'],
    ),
  'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
  'getPostsByAuthor' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getUploadState' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUploadState' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'uploadMediaChunk' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      [],
    ),
  'uploadMediaData' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'media' : IDL.Vec(IDL.Nat8),
    'author' : IDL.Principal,
    'isFinalized' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteChunk' : IDL.Func([IDL.Nat], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'finalizeUpload' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPaginatedPosts' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
    'getPostsByAuthor' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getUploadState' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUploadState' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'uploadMediaChunk' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        [],
      ),
    'uploadMediaData' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };